version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: slotify
      POSTGRES_PASSWORD: slotify_pass
      POSTGRES_DB: slotifydb
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  db_data:
